version: '3'
services:
    mdtopdf:
        build: ./docker/mdtopdf
        container_name: mdtopdf
        ports:
            - 8000:8000
        volumes:
        - ./workdir:/workdir
        tty: true
    servlet:
        build: ./docker/servlet 
        container_name: mdtopdf_servlet
        command: java -cp "lib/*:bin/classes" server.AppServer 8080 / WebContent 
        working_dir: /src
        ports:
            - 8080:8080
        volumes:
        - ./servlet:/src
        tty: true
    # nginx:
    #     image: nginx
    #     container_name: nginx
    #     ports: 
    #         - 80:80
    #     volumes: 
    #         - ./docker/nginx/:/etc/nginx/conf.d/


