version: '3'
services:
    mdtopdf:
        build: ./docker/mdtopdf
        container_name: mdtopdf
        command: go run main.go
        ports:
            - 8000:8000
        volumes:
        - ./workdir:/workdir
        tty: true
    servlet:
        build: ./docker/servlet 
        container_name: mdtopdf_servlet
        command: java -cp "lib/*:bin/classes" server.AppServer 8080 / WebContent 
        working_dir: /src
        ports:
            - 8080:8080
        volumes:
        - ./servlet:/src
        tty: true
    nginx:
        image: nginx:1.17
        container_name: mdtopdf_nginx 
        ports: 
        - 3000:80
        volumes:
        - ./nginx:/etc/nginx/conf.d/
        tty: true
        depends_on:
        - mdtopdf
        - servlet
